#!/bin/bash
#
# tourbillon service daemon init script.
#
# Copyright (C) 2015 The Tourbillon Team
#
#
# chkconfig: 2345 20 80
# description: Start/stop the tourbillon service daemon

### BEGIN INIT INFO
# Provides:	  tourbillon
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the tourbillon agent
# Description:       starts the tourbillon agent using start-stop-daemon
### END INIT INFO

PATH=/usr/local/bin:/usr/bin:/sbin:/bin:/usr/sbin
export PATH


lockfile="/var/lock/subsys/tourbillon"
pidfile="/var/run/tourbillon/tourbillon.pid"
tourbillond="/usr/local/bin/tourbillond"
RETVAL=0

. /etc/init.d/functions



start() {
    echo -n $"Starting tourbillon agent: "
    daemon --user tourbillon --pidfile $pidfile $tourbillond
    RETVAL=$?
    echo
        [ $RETVAL = 0 ] && touch ${lockfile}
        return $RETVAL
}

stop() {
    echo -n $"Stopping tourbillon agent: "
    killproc -p $pidfile $tourbillond
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
}

restart() {
    stop
    start
}

rh_status() {
    status -p $pidfile $tourbillond
    RETVAL=$?
    return $RETVAL
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    status)
        rh_status
    ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 1
esac

exit $RETVAL

